name = "r2-upload-worker"
main = "src/index.js"
compatibility_date = "2023-08-01"

# Your account ID from Cloudflare dashboard
account_id = "your-account-id"

# R2 bucket binding
[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "skybuddy-audio"

# Environment variables
[vars]
ACCOUNT_ID = "your-account-id"
BUCKET_NAME = "skybuddy-audio"